services:
  elasticsearch:
    image: elastic/elasticsearch:9.0.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.5
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "9092:9092"     # Kafka interno (dentro do cluster)
      - "19092:19092"   # Kafka externo (para apps locais)
      - "9644:9644"     # Admin API

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.6.1
    container_name: redpanda-console
    ports:
      - "8090:8080"   # UI do console
    environment:
      KAFKA_BROKERS: redpanda:9092
      REDPANDA_ADMIN_API: http://redpanda:9644
    depends_on:
        - redpanda
  postgres:
    image: postgres:18.0-alpine3.22
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: elasticsearch
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app_net

networks:
  redpanda_net:
      driver: bridge
  app_net:
    driver: bridge
volumes:
  pgdata: